### ISSUE TITLE
Panic on decoding some JPEG images - `unwrap()` in `idct/avx2.rs`

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-image#11]
Samples to reproduce the issue:  [zune-avx2-panic.tar.gz](https://github.com/etemesi254/zune-image/files/10213242/zune-avx2-panic.tar.gz)

These images decode fine in other decoders; zune panics:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', zune-jpeg/src/idct/avx2.rs:258:5
```

Tested on commit 5877c2f2bf984f9f31b4883a1a4df628e5e0ae9b

**Comment by Shnatsel** [comment]
And here's some more, panicking at `avx2.rs:128:9` (different line in the same file):
[zune-avx2-panic-2.tar.gz](https://github.com/etemesi254/zune-image/files/10213315/zune-avx2-panic-2.tar.gz)
