### ISSUE TITLE
crash: assertion `left == right` failed for JPEG

### ISSUE THREAD

**Issue by TheOneric** [etemesi254/zune-image#236]
I stumbled into a crash from a failed assertion on current dev (b3b244df208131a9a931cc9b83527b504b461d66) while running the fuzzer a bit
```
thread '<unnamed>' panicked at /home/gekota/img-fuzz/zune-image/crates/zune-jpeg/src/upsampler/scalar.rs:59:5:
assertion `left == right` failed
  left: 512
 right: 256

stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:408:17
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:363:5
   4: zune_jpeg::upsampler::scalar::upsample_vertical
   5: zune_jpeg::upsampler::scalar::upsample_hv
             at ./src/upsampler/scalar.rs:83:5
   6: zune_jpeg::worker::upsample
             at ./src/worker.rs:402:21
   7: zune_jpeg::mcu::<impl zune_jpeg::decoder::JpegDecoder<T>>::post_process
             at ./src/mcu.rs:418:17
   8: zune_jpeg::mcu::<impl zune_jpeg::decoder::JpegDecoder<T>>::decode_mcu_ycbcr_baseline
             at ./src/mcu.rs:201:13
   9: zune_jpeg::decoder::JpegDecoder<T>::decode_into
             at ./src/decoder.rs:712:13
  10: zune_jpeg::decoder::JpegDecoder<T>::decode
             at ./src/decoder.rs:209:9
  11: decode_buffer::_::__libfuzzer_sys_run
             at ./fuzz/fuzz_targets/decode_buffer.rs:9:13

```

Minimised test file: [zune-jpeg_assertfail.jpg](https://github.com/user-attachments/assets/10e2dd06-1527-4941-be44-629f656be41a)
Even if the file is invalid *(likely, but not sure)*, it probably shouldn't lead to an outright, ungraceful crash.

**Comment by etemesi254** [comment]
Correct, it should not crash.

Looking into it

**Comment by richard-viney** [comment]
I just ran into what appears to be the same or very similar crash when fuzzing a library that depends on zune-jpeg 0.4.14.

If it's helpful, the JPEG file that triggers the issue is here: https://drive.google.com/file/d/1azRp3lT9GAO0JhGCyTTvulaVjUU5_sqQ/view?usp=sharing

**Comment by etemesi254** [comment]
Hi,

Could you try the latest version?

Kind regards,
Caleb

**Comment by richard-viney** [comment]
The panic is also present on latest `main` (4a073b12947f9d1003ae931b7b7cd9da2914d4d8).

I found another panic in 0.4.14 during fuzzing, but that one doesn't reproduce on `main` so I won't open an issue for it. (Unless you'd like it to be added as a test case?)
